from __future__ import annotations

from pathlib import Path


def _ps_escape_single_quoted(value: str) -> str:
    return value.replace("'", "''")


def _render_bootstrap_ps1() -> str:
    return """$ErrorActionPreference = \"Stop\"

$root = Split-Path -Parent $PSScriptRoot
Push-Location $root
try {
    $uv = Get-Command uv -ErrorAction SilentlyContinue
    if (-not $uv) {
        throw \"uv is required but was not found in PATH. Install uv from https://docs.astral.sh/uv/getting-started/installation/.\"
    }

    $localPython = Join-Path $root \".venv\\Scripts\\python.exe\"

    if (-not (Test-Path $localPython)) {
        & uv venv .venv
        if ($LASTEXITCODE -ne 0 -or -not (Test-Path $localPython)) {
            throw \"Local virtual environment creation failed via uv.\"
        }
    }

    & uv pip install --python $localPython -e .
    if ($LASTEXITCODE -ne 0) {
        throw \"Failed to install project dependencies with uv.\"
    }
}
finally {
    Pop-Location
}
"""


def _render_generate_parser_ps1(package_name: str, export_file: str) -> str:
    package_name = _ps_escape_single_quoted(package_name)
    export_file = _ps_escape_single_quoted(export_file)
    return f"""$ErrorActionPreference = \"Stop\"

$root = Split-Path -Parent $PSScriptRoot
Push-Location $root
try {{
    $uv = Get-Command uv -ErrorAction SilentlyContinue
    if (-not $uv) {{
        throw \"uv is required but was not found in PATH. Install uv from https://docs.astral.sh/uv/getting-started/installation/.\"
    }}

    $pythonExe = Join-Path $root \".venv\\Scripts\\python.exe\"
    if (-not (Test-Path $pythonExe)) {{
        throw \"Missing local virtual environment. Run ./scripts/bootstrap.ps1 first.\"
    }}

    $exportFile = '{export_file}'
    if (-not (Test-Path $exportFile)) {{
        throw \"Export file not found: $exportFile\"
    }}

    & uv run --python $pythonExe -m parol_pygen.cli generate --export $exportFile --out . --package '{package_name}'
}}
finally {{
    Pop-Location
}}
"""


def _render_run_proof_ps1(package_name: str, export_file: str) -> str:
    package_name = _ps_escape_single_quoted(package_name)
    export_file = _ps_escape_single_quoted(export_file)
    return f"""$ErrorActionPreference = \"Stop\"

$root = Split-Path -Parent $PSScriptRoot
Push-Location $root
try {{
    $pythonExe = Join-Path $root \".venv\\Scripts\\python.exe\"
    if (-not (Test-Path $pythonExe)) {{
        throw \"Missing local virtual environment. Run ./scripts/bootstrap.ps1 first.\"
    }}

    if (-not (Test-Path '{package_name}')) {{
        & $PSScriptRoot\generate-parser.ps1
    }}

    & $pythonExe -m parol_pygen.cli validate --export '{export_file}'
    & $pythonExe .\proof_runner.py
}}
finally {{
    Pop-Location
}}
"""


def _render_readme(project_name: str, package_name: str, export_file: str) -> str:
    return f"""# {project_name}

Scaffolded parser project generated by `parol-pygen init`.

## Quick start

1. Place your export JSON at `{export_file}`
2. Run `./scripts/bootstrap.ps1`
3. Run `./scripts/generate-parser.ps1`
4. Run `./scripts/run-proof.ps1`

## Generated package

- Package name: `{package_name}`
- Entry parser class: `{package_name}.Parser`
- User semantic action base: `{package_name}.UserActions`
"""


def _render_pyproject(project_name: str) -> str:
    normalized = project_name.lower().replace(" ", "-")
    return f"""[build-system]
requires = [\"setuptools>=68\", \"wheel\"]
build-backend = \"setuptools.build_meta\"

[project]
name = \"{normalized}\"
version = \"0.1.0\"
description = \"Scaffolded parser proof project generated by parol-pygen\"
requires-python = \">=3.10\"
dependencies = [
  \"parol-pygen\",
]
"""


def _render_proof_runner(package_name: str) -> str:
    return f"""from __future__ import annotations

from pathlib import Path

from custom_actions import ProofActions
from {package_name} import Parser


def main() -> int:
    root = Path(__file__).resolve().parent
    sample_file = root / \"sample.txt\"

    if not sample_file.exists():
        raise FileNotFoundError(f\"Missing sample file: {{sample_file}}\")

    text = sample_file.read_text(encoding=\"utf-8\")
    actions = ProofActions()
    parser = Parser(actions=actions)
    result = parser.parse(text)

    print(f\"Accepted: {{result.accepted}}\")
    print(f\"Reductions: {{len(result.reductions)}}\")
    print(f\"Action callbacks: {{actions.reduction_count}}\")
    return 0


if __name__ == \"__main__\":
    raise SystemExit(main())
"""


def _render_custom_actions(package_name: str) -> str:
    return f"""from __future__ import annotations

from {package_name} import UserActions
from {package_name}.nodes import NonTerminalNode


class ProofActions(UserActions):
    def __init__(self) -> None:
        super().__init__()
        self.reduction_count = 0

    def on_non_terminal(self, name: str, node: NonTerminalNode):
        self.reduction_count += 1
        return node
"""


def _render_gitignore(package_name: str) -> str:
    return f""".venv/
__pycache__/
*.pyc
{package_name}/
"""


def scaffold_project(
    out_dir: str | Path,
    project_name: str,
    package_name: str,
    export_file: str,
    force: bool = False,
) -> Path:
    root = Path(out_dir)
    if root.exists() and any(root.iterdir()) and not force:
        raise ValueError(f"Target directory is not empty: {root}. Use --force to overwrite files.")

    root.mkdir(parents=True, exist_ok=True)
    scripts_dir = root / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    files: dict[Path, str] = {
        root / "README.md": _render_readme(project_name, package_name, export_file),
        root / "pyproject.toml": _render_pyproject(project_name),
        root / ".gitignore": _render_gitignore(package_name),
        root / "proof_runner.py": _render_proof_runner(package_name),
        root / "custom_actions.py": _render_custom_actions(package_name),
        root / "sample.txt": "Var abc End\n",
        scripts_dir / "bootstrap.ps1": _render_bootstrap_ps1(),
        scripts_dir / "generate-parser.ps1": _render_generate_parser_ps1(package_name, export_file),
        scripts_dir / "run-proof.ps1": _render_run_proof_ps1(package_name, export_file),
    }

    for path, content in files.items():
        if path.exists() and not force:
            raise ValueError(f"Refusing to overwrite existing file: {path}. Use --force.")
        path.write_text(content, encoding="utf-8")

    return root
